In [1]:
%time


N = 3
  
for i in range(1,N):
  if N in range(1, 10**25):
    N += i
print(N)

CPU times: total: 0 ns
Wall time: 0 ns
6


In [2]:
# 1- island
# 0 - ocean

import numpy as np
import random
import pandas as pd

m = 5
n = 4
x = np.eye(m,n, k=1)

print(x)

print('Number of islands in matrix is: ', np.count_nonzero(x ==1))
'''
larger_matrix = np.array(random.choices(nature, k = 50))
print(larger_matrix)
n = 4
m = 5
print(np.reshape(np.matrix(larger_matrix.flatten(),size = n*m),(n,m)))
'''

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Number of islands in matrix is:  3


'\nlarger_matrix = np.array(random.choices(nature, k = 50))\nprint(larger_matrix)\nn = 4\nm = 5\nprint(np.reshape(np.matrix(larger_matrix.flatten(),size = n*m),(n,m)))\n'